### PR TITLE
Add log package

### LINKED ISSUE #57: Use single instance of logger across the project
Currently each subpackage use it's own instance of a logger. So some of logs get printed some doesn't depending of each logger's logging level

### PR DESCRIPTION
**Pull request by komalsukhani**
Fixes #57

I have created a log package, which is shared by all sub-packages. Log level can be set using TYK_LOGLEVEL environment variable.

### CODE REVIEW

**Comment by letzya** [comment]
@komalsukhani looks good to me. 
2 comments, but we might choose to do it on a separate PR:
- [ ] Would you mind adding more info (using "withFields") where we have errors?
- [ ] Can we change the prefix so something a bit more structured that string concatenation ` logger.Error(tag+" "+errorMsg+": ", rawErr)`?


@buger

**Comment by asoorm** [comment]
Wouldn't it be easier to do:

```
import logger "github.com/TykTechnologies/tyk-identity-broker/log"

var log = logger.Get()
```

Then you don't need to change all the code from `log` to `logger`?

**Comment by letzya** [comment]
@asoorm I think Komal was trying to keep the naming convention similar to the BE. I dont mind either.

**Comment by komalsukhani** [comment]
> @asoorm I think Komal was trying to keep the naming convention similar to the BE. I dont mind either.

Exactly. If you want, I will change it. I think that will easier to review

**Comment by komalsukhani** [comment]
> @komalsukhani looks good to me.
> 2 comments, but we might choose to do it on a separate PR:
> 
>     * [ ]  Would you mind adding more info (using "withFields") where we have errors?
> 
>     * [ ]  Can we change the prefix so something a bit more structured that string concatenation ` logger.Error(tag+" "+errorMsg+": ", rawErr)`?
> 
> 
> @buger

I have made the changes you have suggested. Please let me know if it needs more fixes

**Pull request merged**
