### PR TITLE
Adding SAML role support for Dashboard Users Groups. Example:

### PR DESCRIPTION
**Pull request by bmonteiro**
profiles.json

```
{
...
 "CustomUserGroupField": "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
    "UserGroupMapping": {
      "7149b3c0-5e5d-48b3-a42a-c73ded0bc232": "5f034003ed3dc300012e48a0",
      "ab776d34-1d4c-4ee0-9f4b-9a9cae029f4e": "5f033fa1ed3dc300012e489f"
    }
...
}
```

### CODE REVIEW

**Comment by bmonteiro** [comment]
@joshblakeley this PR is ok for you ?

**Comment by joshblakeley** [comment]
It's just a small change so should be ok - can you remind me what the change enables in terms of enhancing the existing PR?

**Comment by bmonteiro** [comment]
> It's just a small change so should be ok - can you remind me what the change enables in terms of enhancing the existing PR? It seems to just be trimming whitespace but though i would check

It will allow the user to configure SAML roles mapping with dashboard group id via `profiles.json`

`{
...
 "CustomUserGroupField": "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
    "UserGroupMapping": {
      "7149b3c0-5e5d-48b3-a42a-c73ded0bc232": "5f034003ed3dc300012e48a0",
      "ab776d34-1d4c-4ee0-9f4b-9a9cae029f4e": "5f033fa1ed3dc300012e489f"
    }
...
}`

**Comment by joshblakeley** [comment]
That functionailty was already there, you just seem to be doing some string formatting in this PR

**Comment by joshblakeley** [comment]
Was there a compatibility issue for returned values in some way?

**Comment by bmonteiro** [comment]
> Was there a compatibility issue for returned values in some way?

yes, therefore the PR otherwise you cannot have more than 1 role configured

**Comment by joshblakeley** [comment]
Makes sense!

**Pull request merged**
