### PR TITLE
releng: push images for manifests

### PR DESCRIPTION
**Pull request by alephnull**
always push docker images

## Description
The multi-arch docker manifests require the arch specific docker images to build. Thus the docker builds should be pushed always

Als
## Related Issue
https://tyktech.slack.com/archives/CKARCGLEM/p1621348785002500

## How This Has Been Tested
See the status in the _Checks_ tab.

### CODE REVIEW

**Review by gwotg — APPROVED** [review]
Thanks @alephnull, I see no harm - didn't bother to drill through.

**Comment by alephnull** [comment]
Fixes #168

**Comment by excieve** [comment]
@buger Is it fine to merge this now?

**Comment by alephnull** [comment]
This has been superceded by #174. Abandoning.

**Pull request closed without merging**
