### PR TITLE
[TT-2527] Do not cache middleware

### PR DESCRIPTION
**Pull request by buger**
## Description
At the moment the first profile which init SAML will cache, and prevent rest of profiles to properly work.

Fix https://github.com/TykTechnologies/tyk-identity-broker/issues/170

## How This Has Been Tested
I tested it using external TIB, and the steps that I followed are:

- Created 2 profiles, one to SSO to dashboard, another to SSO to portal:
```
 {
        "ID":"saml-sso-dash-login",
        "Name":"",
        "OrgID":"5e2091c4d4aefce60c04fb92",
        "ActionType":"GenerateOrLoginUserProfile",
        "MatchedPolicyID":"",
        "Type":"redirect",
        "ProviderName":"SAMLProvider",
        "CustomEmailField":"",
        "CustomUserIDField":"",
        "ProviderConfig":{
            "CertLocation":"/Users/sredny/.ssh/saml/completo.pem",
            "FailureRedirect":"http://tyk-dashboard:3000/?fail=true",
            "ForceAuthentication":true,
            "IDPMetaDataURL":"https://login.microsoftonline.com/xxxxxxx-xxxxxx-xxxx-xxxx-xxxxxxxxx/federationmetadata/2007-06/federationmetadata.xml?appid=xxxxxx",
            "KeyFile":"/Users/sredny/.ssh/saml/key.pem",
            "SAMLBaseURL":"https://868c0dc6d5ee.ngrok.io/",
            "SAMLEmailClaim":"",
            "SAMLForenameClaim":"",
            "SAMLSurnameClaim":""
        },
        "IdentityHandlerConfig":{
            "DashboardCredential":"e7bc3a2eef2e410757a2f3047679895d"
        },
        "ProviderConstraints":{
            "Domain":"",
            "Group":""
        },
        "ReturnURL":"http://tyk-dashboard:3000/tap",
        "DefaultUserGroupID":"",
        "CustomUserGroupField":"",
        "UserGroupMapping":null,
        "SSOOnlyForRegisteredUsers":false
    },
    {
        "ID": "saml-sso-dev-portal-login",
        "ActionType": "GenerateOrLoginDeveloperProfile",
        "OrgID":"5e2091c4d4aefce60c04fb92",
        "ProviderConfig": {
            "SAMLBaseURL":"https://868c0dc6d5ee.ngrok.io/",
            "FailureRedirect": "http://tyk-portal:3000/portal/login/",
            "IDPMetaDataURL":"https://login.microsoftonline.com/xxxxxx-xxxxxx-xxxxx-xxxxx/federationmetadata/2007-06/federationmetadata.xml?appid=xxxxxxxxx",
            "CertLocation":"/Users/sredny/.ssh/saml/completo.pem",
            "ForceAuthentication": true
        },
        "IdentityHandlerConfig": {
            "DashboardCredential": "e7bc3a2eef2e410757a2f3047679895d"
        },
        "ProviderName": "SAMLProvider",
        "ReturnURL": "http://tyk-portal:3000/sso/",
        "Type": "redirect"
    },
```
- Exposed TIB with ngrok to internet and used the HTTPS link
- In Azure configured SAML as:
Captura de Pantalla 2021-08-06 a la(s) 5 02 11 p  m

- To test Dashboard SSO, I went to: [https://868c0dc6d5ee.ngrok.io/auth/saml-sso-dash-login/SAMLProvider](https://868c0dc6d5ee.ngrok.io/auth/saml-sso-dash-login/SAMLProvider)
- To test Portal SSO, I went to: [https://868c0dc6d5ee.ngrok.io/auth/saml-sso-dev-portal-login/SAMLProvider](https://868c0dc6d5ee.ngrok.io/auth/saml-sso-dev-portal-login/SAMLProvider)
- And I was redirected successfully to dashboard and portal in each case.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Review by sredxny — APPROVED** [review]
Lgtm 🚀

**Comment by buger** [comment]
@sredxny I do not know if it is possible to add test for it. 
But in general feel free to own this branch, I just copied and pasted what worked for customer, and have not actually thought if it is right fix or not.

**Comment by sredxny** [comment]
I updated the PR and considered load certs from files (it was broken), tested as described above. Wondering if we need to remove the /vendor directory 🤔

**Comment by buger** [comment]
Well, as far as I understand, it fixes file loading only when you use external TIB. When used with Dashboard, it probably works.

**Comment by sredxny** [comment]
@buger when we use it embeded then we set a redis CertManager which internally fallbacks in file (if key not found in redis then it tries to read as a file). TIB defaults to file loader, it wasnt working because for fileLoader we do not set an storage (it was nil so it panics: https://github.com/TykTechnologies/tyk/blob/master/certs/manager.go#L349 )

**Review by tbuchaillot — APPROVED** [review]

**Pull request merged**
