### PR TITLE
Support for mongo db as DataLoader

### PR DESCRIPTION
**Pull request by sredxny**
**What was done?**

- Implemented the methods of DataLoader interface for Mongo, so, now we can use this database to persist the data related to the profiles. The methods are: Init, LoadIntoStore and Flush

- Reestructured code of DataLoader, now its a separated package

- Moved configurations to its own package

**Breaking changes**
None

**New block in configuration file**
A block was added to detail the data correspondent for Mongo as DataStorage:

```
"Storage":{
        "storage_type":"mongo",
        "mongo":{
            "mongo_url": "mongodb://tyk-mongo:27017/tyk_tib"
        }
    }
```

The definition for each field is as next:

- storage_type: which storage type you want use, the valid values are: mongo | file. If the block is not present in the config file then File is assumed as default
- mongo.mongo_url: url to connect to the database

**How to test it?**

Just execute TIB as usually you do, but provide a configuration file that contains the block described before, in this case is not needed to pass a profile file as parameter. In the logs you will see that the DataLoader with Mongo was initiated and it loaded the profilles from mongo. To test using Curl do the next steps:

- **Adding a Profile**
```
curl -X POST \
  http://localhost:3010/api/profiles/1 \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: test-secret' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 792' \
  -H 'Content-Type: text/plain' \
  -H 'Host: localhost:3010' \
  -H 'Postman-Token: 22f8732e-f329-4605-a6f8-236167116ee1,48f13a84-068b-46e0-aa2a-205ac92eca70' \
  -H 'User-Agent: PostmanRuntime/7.20.1' \
  -H 'cache-control: no-cache' \
  -d '{
			"ActionType": "GenerateTemporaryAuthToken",
			"ID": "1",
			"IdentityHandlerConfig": {
				"DashboardCredential": "822f2b1c75dc4a4a522944caa757976a",
				"DisableOneTokenPerAPI": false,
				"TokenAuth": {
					"BaseAPIID": "e1d21f942ec746ed416ab97fe1bf07e8"
				}
			},
			"MatchedPolicyID": "5654566b30c55e3904000003",
			"OrgID": "53ac07777cbb8c2d53000002",
			"ProviderConfig": {
				"ExrtactUserNameFromBasicAuthHeader": true,
				"OKCode": 200,
				"OKRegex": "origin",
				"OKResponse": "ewogICJvcmlnaW4iOiAiNjIuMjMyLjExNC4yNTAsIDE3OC42Mi4xMS42MiwgMTc4LjYyLjExLjYyIgp9Cg==",
				"TargetHost": "http://sharrow.tyk.io/ba-1/"
			},
			"ProviderConstraints": {
				"Domain": "",
				"Group": ""
			},
			"ProviderName": "ProxyProvider",
			"ReturnURL": "",
			"Type": "passthrough"
}
```
- **Saving in Mongo**
Is the equivalent for flushing changes, it will create as well a backup with the timestamp as name of collection.

```
curl -X POST \
  http://localhost:3010/api/profiles/save \
  -H 'Authorization: test-secret' \
  -H 'Postman-Token: f86621b3-8c61-4b14-ad2a-5a6c79d371c4' \
  -H 'cache-control: no-cache'
```

After executing these 2 steps you should be able to check against the database that the record was stored and also it's loaded in the selected backend (redis or in-memory)

**Notes:**

- In this PR was started the modularization of TIB in more granular packages that will allow later the integration in tyk-dashboard in a more friendly way.
- Is needed to write more tests.

### CODE REVIEW

**Comment by letzya** [comment]
A free questions
- Maybe I missed it but is there an option to delete a profile or all profiles from the data store?
- can we support Postgres? (There’s a small pr in the dashboard that can help)

**Comment by buger** [comment]
Postgress is for sure outside of this scope. We do not use it anywhere. 
If we accelerate our plan of switching dash to postgress, then TIB will come next too. 

Regarding method to delete profile it is for sure will be very handy.

**Comment by sredxny** [comment]
@letzya @buger we have an endpoint to delete already, and it synchronizes the information by triggering the Flush method. So the flow would be as next:

1. user call Delete endpoint
2. TIB removes the profile from the backend (in-memory or redis)
3. Flush handler is called via /save endpoint
4. Flush handler will create a backup collection named _collection+timestamp_ and will store in the profiles collection what is currently loaded in the backend

**Now the questions that raises are:**

1. Normally, when the /save endpoint is called?
2. Should we flush everytime that a create/update/delete action is triggered?
3. In the current flow for files, each time that flush is called a new file for backup is created, I did the same for mongo but creating a new collection. So, in the future when we integrate TIB inside Dashboard then we might be having a database with a lot of collections, thing that doesn't seem to be the cleanest way to save backups. What do you think about having one single collection where every document represent a backup?

**Comment by buger** [comment]
It does not feel like we need save endpoint anymore in this setup.

**Comment by sredxny** [comment]
@buger then going to remove /save endpoint and call flush anytime that a change happens

**Comment by sredxny** [comment]
**Update:** Some changes were implemented according to what was discussed above:

- Removed endpoint /save to flush profiles and save in storage (file or mongo)

- For Mongo Backups, now they are stored in one single collection, for every document we store: timestamp and the array of profiles, the collection is called _profiles_backup_.

- Added test to check the correct creation of one mongo data loader

@letzya @buger @matiasinsaurralde please check

**Comment by matiasinsaurralde** [comment]
> Update: Some changes were implemented according to what was discussed above:
> 
> Removed endpoint /save to flush profiles and save in storage (file or mongo), now anytime that a Create, Update or Delete action if performed then we flush to the database
> 
> For Mongo Backups, now they are stored in one single collection, for every document we store: timestamp and the array of profiles, the collection is called profiles_backup.
> 
> Added test to check the correct creation of one mongo data loader
> 
> @letzya @buger @matiasinsaurralde please check

Looks good so far!

**Comment by buger** [comment]
merged as part of https://github.com/TykTechnologies/tyk-identity-broker/pull/83

**Pull request closed without merging**
