### PR TITLE
Update Cloudsmith url

### PR DESCRIPTION
**Pull request by vesko-tyk**
Change Cloudsmith url

### CODE REVIEW

**Comment by alephnull** [comment]
This should align with https://github.com/TykTechnologies/tyk-identity-broker/pull/154

**Comment by vesko-tyk** [comment]
Sure, will rebase this PR once https://github.com/TykTechnologies/tyk-identity-broker/pull/154 is merged

**Comment by alephnull** [comment]
The CI failure should be solved by rebasing master.

**Review by alephnull — APPROVED** [review]
LGTM.

**Pull request merged**
