### PR TITLE
Use regular Dashbord API instead of Admin API for SSO

### LINKED ISSUE #55: Add support for Dashboard SSO API
GW part https://github.com/TykTechnologies/tyk/issues/2103

If we are going to retire the "admin dashboard endpoint" we can update TIB to use the new dashboard endpoint

### PR DESCRIPTION
**Pull request by furkansenharputlu**
Fixes #55

### CODE REVIEW

**Comment by letzya** [comment]
@furkansenharputlu @buger these are breaking changes

**Comment by furkansenharputlu** [comment]
@letzya The `api/sso` endpoint is used internally in TIB. I mean for a user, is there any change ?

**Comment by buger** [comment]
@furkansenharputlu it will break if people upgrade TIB but not upgrade dashboard (common pattern).

**Comment by joshblakeley** [comment]
@furkansenharputlu are you still working on this?

**Comment by furkansenharputlu** [comment]
@buger @letzya Look at the issue #55. It says retiring the admin api, so TIB should use regular dashboard api rather than admin API. People should upgrade their dashboard if they want to upgrade their TIB to solve the problem. Let's say a new feature needing change in both Gateway and Dashboard. If user updates one of them but not the other one, the feature will not work properly. I think this is a similar situation.

**Comment by buger** [comment]
Lets better do it in a backward compatible way:
If `dashboardUserAPICred` is specified use new endpoint, if its empty use admin endpoint.

**Comment by furkansenharputlu** [comment]
@buger It is same thing that I said because `dashboardUserAPICred` is used by other endpoints so it is specified every time. This means it will never use admin endpoint as wel.

**Comment by furkansenharputlu** [comment]
However, maybe we can say if `t.DashboardConfig.AdminSecret` is specified, use admin API, otherwise use regular API. Wdyt ?

**Comment by buger** [comment]
I would not touch the global option. Note that admin API has own unique features, which can't be replicated by Dash API: access to multiple orgs with a single secret. 

You may want to use both settings in your pump comfig.

**Comment by buger** [comment]
Also does `dashboardUserAPICred` specified on profile level or config level?

Can you post example profile configuration?

**Comment by furkansenharputlu** [comment]
```[{
    "ActionType": "GenerateOrLoginUserProfile",
    "ID": "1",
    "OrgID": "5a564276159d760291b6fe10",
    "IdentityHandlerConfig": {
        "DashboardCredential": "b5fccb8f4d0b43fb52717fd564844399"
    },
    "ProviderConfig": {
        "CallbackBaseURL": "http://localhost:3010",
        "FailureRedirect": "http://tyk-dashboard:3000/?fail=true",
        "UseProviders": [{
            "Key": "372710836929-gi3klrk8fobrvlsfgorlvctonti2aedj.apps.googleusercontent.com",
            "Name": "gplus",
            "Secret": "4w2ObHicTb96KY3Owhx4cz5M"
        }]
    },
    "ProviderName": "SocialProvider",
    "ReturnURL": "http://tyk-dashboard:3000/tap",
    "Type": "redirect"
},
{
    "ActionType": "GenerateOrLoginUserProfile",
    "ID": "2",
    "OrgID": "5a564276159d760291b6fe10",
    "IdentityHandlerConfig": {
        "DashboardCredential": "7e391702b78b475d60959093d15a3c63"
    },
    "ProviderConfig": {
        "CallbackBaseURL": "http://localhost:3010",
        "FailureRedirect": "http://tyk-dashboard:3000/?fail=true",
        "UseProviders": [{
            "Key": "0oadl1qnzbn3mnCtG0h7",
            "Secret": "90YS27eaRG1cBkqJJ5Twcwjw9dl3mfTSnXSKf-2J",
            "DiscoverURL": "https://dev-245115.oktapreview.com/.well-known/openid-configuration",
            "Name": "openid-connect"
        }]
    },
    "ProviderName": "SocialProvider",
    "ReturnURL": "http://tyk-dashboard:3000/tap",
    "Type": "redirect"
}
]````

**Comment by buger** [comment]
Looks good!

**Comment by buger** [comment]
Just to recap, now for backward compatibility logic is: 
1) Try Dashboard API first, if got 404
2) Try Admin API

**Pull request merged**
