### PR TITLE
[TD-1698] Fix-release-workflow-tyk-identity-broker

### PR DESCRIPTION
**Pull request by ermirizio**
Update/Sync Releng templates for tyk-identity-broker:master

:robot: Beep, boop, this PR has been generated by [automation](https://github.com/TykTechnologies/gromit/blob/master/cmd/policy.go) at 2023-03-23 17:17:41.905634 &#43;0000 UTC

This PR updates the release engineering specific code in the master branch of tyk-identity-broker, and has been generated because some releng code was changed, and the corresponding templates were updated.

These changes should be limited to the `ci/` directory and `.github` directory. This PR should be automatically merged with the branch protection rules are satisfied.

If you think this was made by mistake, or if merging this might cause any instabilities, please bring it up on Slack or log a jira in the TD project.

### CODE REVIEW

**Comment by ermirizio** [comment]
@tbuchaillot dont forget about this one

**Comment by tbuchaillot** [comment]
> @tbuchaillot dont forget about this one

@ermirizio any idea why 1.15 CI job is still required in master when we have 1.16 in our tf files? https://github.com/TykTechnologies/tyk-identity-broker/blob/master/repo-policy/main.tf#L39

**Comment by alephnull** [comment]
Can this one be closed?

**Review by sredxny — APPROVED** [review]
✅

**Pull request merged**
