### PR TITLE
TT-4685 support for comma separated groups claim

### PR DESCRIPTION
**Pull request by sredxny**
## Description
Allow users to set a character in which the user-groups claims will be splitted in. Some IDPs returns a list of groups and the way how they need to get splited changed from idp to idp, some of them use a blank space but some others (as azure) send it separated by comma, hence was added a new config option to the profiles to stablish which character do you want to use to separate the claim, it will default to blankspace to maintain backward compatibility, but you can set any character.

If you want to modify the default behavior then just add the configuration `UserGroupSeparator` in the profile, it should be a string value. Eg: `UserGroupSeparator: ","`

## Related Issue
https://tyktech.atlassian.net/browse/TT-4685

## Motivation and Context
Unblock client and be prepared for different IDPs

## How This Has Been Tested
- Ran tests sending different groups configurations

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Review by tbuchaillot — APPROVED** [review]
Looks good! How would the user set this new config in the dashboard? only by raw profile editing?

**Comment by sredxny** [comment]
@tbuchaillot yes only editing the raw profile by now

**Review by matiasinsaurralde — APPROVED** [review]
LGTM

**Pull request merged**
